//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkMusic.OldDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldDbEntities : DbContext
    {
        public OldDbEntities()
            : base("name=OldDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Mp3s> Mp3s { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<PossibleDuplicate> PossibleDuplicates { get; set; }
        public virtual DbSet<RCDC> RCDCs { get; set; }
        public virtual DbSet<StaticPlaylist> StaticPlaylists { get; set; }
        public virtual DbSet<StaticPlaylistTrack> StaticPlaylistTracks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TagCategory> TagCategories { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
