//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkMusic.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleDuplicate
    {
        public int TrackID { get; set; }
        public bool Ignore { get; set; }
    
        public virtual Mp3s Mp3s { get; set; }
    }
}
