//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkMusic.OldDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticPlaylistTrack
    {
        public int PlaylistId { get; set; }
        public string RelativePath { get; set; }
        public int TrackNumber { get; set; }
    
        public virtual StaticPlaylist StaticPlaylist { get; set; }
    }
}
